#pyproject.toml

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -vv"
testpaths = [
    "tests", 
    "integration",
]

markers = [
    "unit: Testes unitários",
    "integration: Testes de integração", 
    "high: Prioridade alta",
    "medium: Prioridade média",
    "low: Prioridade baixa"
]

[tool.flake8]
exclude = [".venv", "build"]
max-line-length = 79
#extend-ignore = "W293"